; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7F91BD6B-DAFC-43ED-A158-10E3B4FFEB96}
AppName=TestApp
AppVersion=1.8.0
;AppVerName=TestApp 1.8.0
DefaultDirName={autopf}\TestApp
UninstallDisplayIcon={app}\TestApp.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Vikn codes\testapp\installer
OutputBaseFilename=TestApp
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Vikn codes\testapp\build\windows\x64\runner\Release\TestApp.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Vikn codes\testapp\build\windows\x64\runner\Release\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Vikn codes\testapp\build\windows\x64\runner\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: "C:\Vikn codes\testapp\updater\updater.exe"; DestDir: "{app}"; Flags: ignoreversion

[Registry]
Root: HKA; Subkey: "Software\Classes\.myp\OpenWithProgids"; ValueType: string; ValueName: "TestAppFile.myp"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\TestAppFile.myp"; ValueType: string; ValueName: ""; ValueData: "TestApp File"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\TestAppFile.myp\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\TestApp.exe,0"
Root: HKA; Subkey: "Software\Classes\TestAppFile.myp\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\TestApp.exe"" ""%1"""

[Icons]
Name: "{autoprograms}\TestApp"; Filename: "{app}\TestApp.exe"
Name: "{autodesktop}\TestApp"; Filename: "{app}\TestApp.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\TestApp.exe"; Description: "{cm:LaunchProgram,TestApp}"; Flags: nowait postinstall skipifsilent

