; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{3B2D9118-6911-4B36-971C-5994638297E8}
AppName=TestApp
AppVersion=1.2.0
;AppVerName=TestApp 1.2.0
DefaultDirName={autopf}\TestApp
UninstallDisplayIcon={app}\TestApp.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Vikn codes\testapp\installer
OutputBaseFilename=TestApp
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Vikn codes\testapp\build\windows\x64\runner\Release\TestApp.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Vikn codes\testapp\build\windows\x64\runner\Release\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Vikn codes\testapp\build\windows\x64\runner\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\TestApp"; Filename: "{app}\TestApp.exe"
Name: "{autodesktop}\TestApp"; Filename: "{app}\TestApp.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\TestApp.exe"; Description: "{cm:LaunchProgram,TestApp}"; Flags: nowait postinstall skipifsilent

